services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2025-latest
        restart: unless-stopped
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=${DB_PASSWORD}
            - MSSQL_PID=Developer
        volumes:
            - mssql_data:/var/opt/mssql
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -C -Q "SELECT 1" || exit 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        deploy:
            resources:
                limits:
                    cpus: "2.00"
                    memory: 2G
        networks:
            - kon_network
    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            mssql:
                condition: service_healthy
        environment:
            - FORCE_COLOR=1
        env_file:
            - .env.prod
        networks:
            - kon_network
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - "5173:80"
        env_file:
            - .env.prod
        depends_on:
            - backend
        networks:
            - kon_network

volumes:
    mssql_data:

networks:
    kon_network:
