### Register a new administrator
POST http://localhost:3000/administrators/register
Content-Type: application/json

{
  "firstName": "Mario",
  "lastName": "Rossi",
  "email": "mario.rossi@example.com",
  "password": "PasswordSicura123!"
}
